#**Beginner Level**

***NumPy***

Create a 1D NumPy array with integers from 10 to 50.


In [ ]:
import numpy as np
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Generate a 3x3 array of random numbers between 0 and 1

In [ ]:
np.random.rand(3,3)

array([[0.25371728, 0.90227095, 0.45223369],
       [0.14238477, 0.5757541 , 0.17416046],
       [0.11187988, 0.98192826, 0.5689862 ]])

Find the mean, median, and standard deviation of the following array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
val,count=np.unique(arr,return_counts=True)
ind = np.argmax(count)
mode=val[ind]
print(f' mean : {np.mean(arr)} \n median : {np.median(arr)} \n standard deviation : {np.std(arr)} \n mode : {mode}')

 mean : 3.5 
 median : 3.5 
 standard deviation : 1.707825127659933 
 mode : 1


Replace all even numbers in a NumPy array with -1.

In [ ]:
arr = np.array([1, 3, 3, 4, 5, 6])
for i,j in enumerate(arr):
  if j%2==0:
    arr[i]=-1
arr


array([ 1,  3,  3, -1,  5, -1])

***Pandas***

In [ ]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Los Angeles', 'Chicago']}
df=pd.DataFrame(data)
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

Select all rows where "Age" is greater than 28

In [ ]:
df[df['Age']>28]

Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

Add a new column "Salary" with values [50000, 60000, 70000] to the DataFrame created above

In [ ]:
df=df.assign(Salary=[50000, 60000, 70000])
df

Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

Rename the column "City" to "Location"

In [ ]:
df.rename(columns={'City':'Location'},inplace=True)
df

Name  Age     Location  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

#**Intermediate Level**

***NumPy***

Create a 4x4 matrix with random integers between 1 and 100 and replace all elements greater than 50 with 50.

In [ ]:
arr=np.random.randint(1,101,size=16)

In [ ]:
arr=arr.reshape(4,4)
arr

array([[  4,  99,  63,  80],
       [ 72,  49,  62,  54],
       [ 77,  33,  71,  32],
       [ 25,  67,  15, 100]])

In [ ]:
for i in np.ndindex(arr.shape):
  if arr[i]>50:
    arr[i]=50
arr

array([[ 4, 50, 50, 50],
       [50, 49, 50, 50],
       [50, 33, 50, 32],
       [25, 50, 15, 50]])

Flatten a 2D array into a 1D array using both ravel() and flatten() methods. Explain the difference.

In [ ]:
print(arr.ravel()) # Returns a view , faster , memory efficient , changes affect original
print(arr.flatten()) # returns copy , slow , more memory , return writable array

[ 4 50 50 50 50 49 50 50 50 33 50 32 25 50 15 50]
[ 4 50 50 50 50 49 50 50 50 33 50 32 25 50 15 50]


In [ ]:
k=arr.ravel()
k[0]=0

array([ 0, 50, 50, 50])

In [ ]:
arr

array([[ 0, 50, 50, 50],
       [50, 49, 50, 50],
       [50, 33, 50, 32],
       [25, 50, 15, 50]])

In [ ]:
l=arr.flatten()
l[0]=4
arr[0]

array([ 0, 50, 50, 50])

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.matmul(A,B)) # for multi dimension also
print(np.dot(A,B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Extract the unique elements from the following array and count their occurrences:

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
i,j=np.unique(arr,return_counts=True)
for i in range(len(i)):
  print(f'{i}"s frequency : {j[i]}')

0"s frequency : 1
1"s frequency : 2
2"s frequency : 1
3"s frequency : 3
4"s frequency : 1


***Pandas***

Load a CSV file

In [ ]:
df=pd.read_csv(r'/content/sample.csv')
df.head(10)

Name   Age         City   Salary
0    Alice  25.0     New York  70000.0
1      Bob  30.0  Los Angeles  80000.0
2  Charlie  35.0     New York  65000.0
3    David  40.0      Chicago  90000.0
4      Eva  28.0      Chicago  72000.0
5    Frank   NaN  Los Angeles  81000.0
6    Grace  38.0     New York      NaN
7    Helen  50.0      Chicago  85000.0
8      Ian   NaN  Los Angeles  79000.0
9     Jane  29.0     New York  68000.0

Group the DataFrame by a specific column

In [ ]:
df.groupby('City')['Salary'].mean()

City
Chicago        82333.333333
Los Angeles    80000.000000
New York       67666.666667
Name: Salary, dtype: float64

Handle missing data in a DataFrame by:

In [ ]:
# Replacing
sal_mean=df['Salary'].mean()
df['Salary']=df['Salary'].fillna(sal_mean)

# Dropping
df.dropna(subset=['Age'],axis=0,inplace=True)
df

Name   Age         City        Salary
0    Alice  25.0     New York  70000.000000
1      Bob  30.0  Los Angeles  80000.000000
2  Charlie  35.0     New York  65000.000000
3    David  40.0      Chicago  90000.000000
4      Eva  28.0      Chicago  72000.000000
6    Grace  38.0     New York  76666.666667
7    Helen  50.0      Chicago  85000.000000
9     Jane  29.0     New York  68000.000000

In [ ]:
df.sort_values(by=['Age','Salary',],ascending=[1,0],inplace=True)
df

Name   Age         City        Salary
0    Alice  25.0     New York  70000.000000
4      Eva  28.0      Chicago  72000.000000
9     Jane  29.0     New York  68000.000000
1      Bob  30.0  Los Angeles  80000.000000
2  Charlie  35.0     New York  65000.000000
6    Grace  38.0     New York  76666.666667
3    David  40.0      Chicago  90000.000000
7    Helen  50.0      Chicago  85000.000000

# **Advanced Level**

***NumPy***

Implement matrix multiplication manually (without using np.dot or @).

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

if A.shape[1]==B.shape[0]:
  C=np.zeros((A.shape[0],B.shape[1]))
  for i in range(A.shape[0]):
    for j in range(B.shape[1]):
      for l in range(B.shape[0]):
        C[i][l]+=A[i][l]*B[l][j]
  print(C)

else:
  print('not possible')

[[11. 30.]
 [33. 60.]]


Create a 3D array of shape (3, 4, 5) filled with random integers. Normalize the array values to the range 0-1.

In [ ]:
arr=np.random.randint(1,100,60).reshape(3,4,5).astype('float')
mea=np.mean(arr)
stda=np.std(arr)
for i in np.ndindex(arr.shape):
  arr[i]=(arr[i]-mea)/stda
arr

array([[[-1.43614754, -0.80870444,  1.45706231,  0.72504536,
          0.48103971],
        [ 0.65532946, -0.18126134,  1.31763051, -0.21611929,
         -0.32069314],
        [-1.22699984, -1.05271009, -1.54072139,  1.70106796,
         -0.73898854],
        [-1.54072139, -1.05271009, -0.70413059,  1.38734641,
          1.59649411]],

       [[-1.50586344,  0.93419306,  0.37646586, -1.43614754,
          0.06274431],
        [ 0.27189201, -0.21611929,  0.23703406,  1.8056418 ,
         -0.21611929],
        [ 0.06274431,  0.75990331,  0.13246021, -1.22699984,
         -0.87842034],
        [-1.19214189,  1.17819871,  0.55075561, -0.32069314,
         -1.47100549]],

       [[ 1.35248846, -0.52984084,  1.77078385,  0.62047151,
          0.30674996],
        [-1.22699984, -0.91327829,  1.00390896,  0.37646586,
          1.35248846],
        [-0.84356239,  0.51589766, -1.43614754,  0.89933511,
          0.27189201],
        [-1.29671574, -0.35555109,  0.20217611,  1.00390896,
          0

In [ ]:
arr=np.random.randint(1,100,60).reshape(3,4,5).astype('float')
mini=np.min(arr)
maxi=np.max(arr)
if mini!=maxi:
  for i in np.ndindex(arr.shape):
    arr[i]=(arr[i]-mini)/(maxi-mini)
arr

array([[[0.375     , 0.98958333, 0.125     , 0.78125   , 0.86458333],
        [0.84375   , 0.34375   , 0.26041667, 0.5625    , 0.95833333],
        [0.57291667, 0.51041667, 0.60416667, 0.39583333, 0.41666667],
        [0.3125    , 0.21875   , 0.61458333, 0.66666667, 1.        ]],

       [[0.61458333, 0.23958333, 0.60416667, 0.14583333, 0.25      ],
        [0.78125   , 0.71875   , 0.77083333, 0.91666667, 0.01041667],
        [0.125     , 0.1875    , 0.08333333, 0.33333333, 0.70833333],
        [0.125     , 0.57291667, 0.38541667, 0.14583333, 0.32291667]],

       [[0.625     , 0.95833333, 0.69791667, 0.15625   , 0.63541667],
        [0.98958333, 0.63541667, 0.86458333, 0.86458333, 0.01041667],
        [0.72916667, 0.35416667, 0.73958333, 0.05208333, 0.9375    ],
        [0.01041667, 0.4375    , 0.0625    , 0.5       , 0.        ]]])

In [ ]:
def inverse(arr):
  deter=np.linalg.det(arr)
  if deter!=0:
    print(f" since determinent is {deter} inverse exists")
    a_inv=np.linalg.inv(arr)

    return a_inv
  else:
    print(f" since determinent is {deter} inverse does not exists")

arr=np.random.randint(1,101,size=16).reshape(4,4)
print('inverse is : \n',inverse(arr))


 since determinent is -2433423.9999999953 inverse exists
inverse is : 
 [[-0.00034437  0.01624871 -0.02638546  0.0150619 ]
 [ 0.05924492 -0.09134125  0.06913879 -0.02559028]
 [ 0.0245432   0.00186404 -0.00257169 -0.01617803]
 [-0.06417706  0.07107516 -0.04250184  0.03128596]]


In [ ]:
import numpy as np

def simulate_markov_chain(P, initial_state, n_steps):

    n_states = P.shape[0]
    states = np.zeros(n_steps + 1, dtype=int)
    states[0] = initial_state

    current = initial_state
    for t in range(n_steps):
        current = np.random.choice(n_states, p=P[current])
        states[t + 1] = current

    return states

P = np.array([
        [0.7, 0.2, 0.1],
        [0.3, 0.4, 0.3],
        [0.2, 0.3, 0.5]
])

print("Transition Matrix:")
print(P)
states = simulate_markov_chain(P, 0, 10)
print(f"states: {states}")
print(f"State frequencies: {np.bincount(states) / len(states)}")

Transition Matrix:
[[0.7 0.2 0.1]
 [0.3 0.4 0.3]
 [0.2 0.3 0.5]]
states: [0 0 2 2 2 2 1 1 2 2 1]
State frequencies: [0.18181818 0.27272727 0.54545455]


***Pandas***

In [ ]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [85, 90, 95]})

df1.set_index('ID').join(df2.set_index('ID'),how='outer')

Name  Score
ID                
1     Alice   85.0
2       Bob   90.0
3   Charlie    NaN
4       NaN   95.0

In [ ]:
pd.merge(df1,df2,on='ID',how='outer')

ID     Name  Score
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie    NaN
3   4      NaN   95.0

In [ ]:
df = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02',
             '2024-01-02', '2024-01-03', '2024-01-03', '2024-01-03'],
    'City': ['New York', 'London', 'Tokyo', 'New York', 'London',
             'Tokyo', 'New York', 'London', 'Tokyo'],
    'Temperature': [32, 45, 28, 35, 42, 30, 33, 40, 29],
    'Age': [25, 8, 65, 45, 12, 70, 30, 85, 5]
})

df

Date      City  Temperature  Age
0  2024-01-01  New York           32   25
1  2024-01-01    London           45    8
2  2024-01-01     Tokyo           28   65
3  2024-01-02  New York           35   45
4  2024-01-02    London           42   12
5  2024-01-02     Tokyo           30   70
6  2024-01-03  New York           33   30
7  2024-01-03    London           40   85
8  2024-01-03     Tokyo           29    5

In [ ]:
piv_df=df.pivot(index='Date',columns='City',values='Temperature')
piv_df

City        London  New York  Tokyo
Date                               
2024-01-01      45        32     28
2024-01-02      42        35     30
2024-01-03      40        33     29

In [ ]:
df['Age_Category'] = df['Age'].apply(lambda x: 'child' if x < 18 else 'adult' if x <= 60 else 'senior')

In [ ]:
df

Date      City  Temperature  Age Age_Category
0  2024-01-01  New York           32   25        adult
1  2024-01-01    London           45    8        child
2  2024-01-01     Tokyo           28   65       senior
3  2024-01-02  New York           35   45        adult
4  2024-01-02    London           42   12        child
5  2024-01-02     Tokyo           30   70       senior
6  2024-01-03  New York           33   30        adult
7  2024-01-03    London           40   85       senior
8  2024-01-03     Tokyo           29    5        child

In [ ]:
seen_rows = set()
first_indi= []

for i, row in df.iterrows():
    row_tuple = tuple(row.values)
    print(row_tuple)
    if row_tuple not in seen_rows:
        seen_rows.add(row_tuple)
        first_indi.append(i)

df_clean = df.iloc[first_indi]

df_clean

('2024-01-01', 'New York', 32, 25, 'adult')
('2024-01-01', 'London', 45, 8, 'child')
('2024-01-01', 'Tokyo', 28, 65, 'senior')
('2024-01-02', 'New York', 35, 45, 'adult')
('2024-01-02', 'London', 42, 12, 'child')
('2024-01-02', 'Tokyo', 30, 70, 'senior')
('2024-01-03', 'New York', 33, 30, 'adult')
('2024-01-03', 'London', 40, 85, 'senior')
('2024-01-03', 'Tokyo', 29, 5, 'child')


Date      City  Temperature  Age Age_Category
0  2024-01-01  New York           32   25        adult
1  2024-01-01    London           45    8        child
2  2024-01-01     Tokyo           28   65       senior
3  2024-01-02  New York           35   45        adult
4  2024-01-02    London           42   12        child
5  2024-01-02     Tokyo           30   70       senior
6  2024-01-03  New York           33   30        adult
7  2024-01-03    London           40   85       senior
8  2024-01-03     Tokyo           29    5        child

In [ ]:
indi = df.index[~df.duplicated()]

new_df = df.iloc[indi]

In [ ]:
new_df

Date      City  Temperature  Age Age_Category
0  2024-01-01  New York           32   25        adult
1  2024-01-01    London           45    8        child
2  2024-01-01     Tokyo           28   65       senior
3  2024-01-02  New York           35   45        adult
4  2024-01-02    London           42   12        child
5  2024-01-02     Tokyo           30   70       senior
6  2024-01-03  New York           33   30        adult
7  2024-01-03    London           40   85       senior
8  2024-01-03     Tokyo           29    5        child